POST http://localhost:3000/vendors
content-type: application/json

{
  "Name": "Vendor",
  "Description": "Test Vendor"
}

###
GET http://localhost:3000/vendors
content-type: application/json

###
GET http://localhost:3000/vendors/1
content-type: application/json
