POST http://localhost:3000/vendors
content-type: application/json

{
  "Name": "Vendor",
  "Description": "Test Vendor"
}

###
GET http://localhost:3000/vendors
content-type: application/json

###
GET http://localhost:3000/vendors/2
content-type: application/json

###
PUT http://localhost:3000/vendors
content-type: application/json

{
  "ID": 1,
  "Name": "Updated Vendor",
  "Description": "Test updating vendor"
}

###
DELETE http://localhost:3000/vendors/3
content-type: application/json