POST http://localhost:3000/signup
content-type: application/json

{
  "Email": "mail5@mail.com",
  "Password": "FakePass"
}

###
POST http://localhost:3000/login
content-type: application/json

{
  "Email": "mail2@mail.com",
  "Password": "FakePass"
}